CREATE TABLE TB_IMAGES

(
    ImageId VARCHAR2(10),
    SuspeitoId VARCHAR2(10),
    DescricaoImage VARCHAR2(20),
    URL VARCHAR2(300)

)

ALTER TABLE TB_IMAGES ADD CONSTRAINT PK_TB_IMAGES PRIMARY KEY (ImageId);

CONSTRAINT PK_TB_IMAGES PRIMARY KEY (SuspeitoId);